packages:
  hal: !include
    file: lilygo_t3_s3_hal.yaml
  resources: !include
    file: resources.yaml
  version: !include
    file: version.yaml

external_components:
  - source: 
      type: git
      url: https://github.com/IoTLabs-pl/ESPHome-Components
      ref: ${esphome_components_version}
    components:
      - wmbus_common
      - wmbus_radio
      - wmbus_meter
  - source: 
      type: git
      url: https://github.com/IoTLabs-pl/wM-Bus-Gateway
      ref: ${wmbus_gateway_version}
    components:
      - wmbus_gateway

esphome:
  name: wmbus-gateway
  friendly_name: wM-Bus Gateway
  comment: wM-Bus Gateway for ESPHome
  project:
    name: IoTLabs.wM-Bus Gateway
    version: ${wmbus_gateway_version}

wmbus_gateway:
  resources:
    font_large: font_large
    font_small: font_small
    qrcode: qrcode
    logo: logo

logger:
  level: debug
  baud_rate: 115200
  logs:
    light: INFO
